# PBS (Professional Backup Script)
# By Brainzman (u/Brainzman, Brainzman#9780)

# Remove old Backup
rm backups/config/*
rm -r backups/worlds/*

# Backup stuff
# config file
cp ~/paper-1132/{*.yml,*.json} backups/config
# world(s)
cp -r ~/paper-1132/{world,cart,themetest,spawn} backups/worlds

# Add all file
git add .

# Commit + Fancy Message
git commit -m  "Backup at $(date)"

# Push to Github
git push origin master
